# Site settings
title: My Portfolio
default_author: Sam Cookson
description: "Online Portfolio of Sam Cookson"  # used in site head

# register on google analytics and replace this token
# google_analytics: UA-75681059-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.

# footer details. Deleting the value would remove it from footer.
github_username:  sambow
email: sbcskyline18@gmail.com
copyright_name: Sam Cookson
rss : true

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
